In [19]:
import numpy as np

# Generate array 'a' of shape (10, 20) with random elements
a = np.random.randint(0, 10, (2,3))

# Generate array 'b' of shape (20, 20) with random elements
b = np.random.randint(0, 10, (3, 3))

# Generate array 'c' of shape (20, 1) with random elements
c = np.random.randint(0, 10, (1, 3))

print(a@b)
print(c)
print(a@b + c)
print(c[0, 0:2])

[[39 21 13]
 [58 34 29]]
[[5 4 2]]
[[44 25 15]
 [63 38 31]]
[5 4]
